// const templateActionTypes = {
//   FETCH_TEMPLATES_START: "FETCH_TEMPLATES_START",
//   FETCH_TEMPLATES_SUCCESS: "FETCH_TEMPLATES_SUCCESS",
//   FETCH_TEMPLATES_ERROR: "FETCH_TEMPLATES_ERROR",
// };

export const FETCH_TEMPLATES_START = "FETCH_TEMPLATES_START";
export const FETCH_TEMPLATES_SUCCESS = "FETCH_TEMPLATES_SUCCESS";
export const FETCH_TEMPLATES_ERROR = "FETCH_TEMPLATES_ERROR";
