export const FETCH_TEMPLATES_START = "FETCH_TEMPLATES_START";
export const FETCH_TEMPLATES_SUCCESS = "FETCH_TEMPLATES_SUCCESS";
export const FETCH_TEMPLATES_ERROR = "FETCH_TEMPLATES_ERROR";
export const LOAD_NEW_PAGE = "LOAD_NEW_PAGE";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";
export const SORT_BY_CATEGORY = "SORT_BY_CATEGORY";
export const SORT_BY_NAME = "SORT_BY_NAME";
export const SORT_BY_DATE = "SORT_BY_DATE";
